"""Database helpers exposed through the structured app package."""

from database import (
    add_student,
    create_note,
    create_user,
    delete_note,
    ensure_note_seed,
    get_connection,
    get_notes,
    get_student,
    get_user_by_email,
    get_user_by_id,
    get_users,
    get_user_progress,
    initialize_database,
    save_learning_progress,
    save_local_progress,
    save_local_submission,
    set_note_pinned,
    update_note,
    update_user_profile,
    upsert_content_item,
    user_payload,
)

__all__ = [
    "add_student",
    "create_note",
    "create_user",
    "delete_note",
    "ensure_note_seed",
    "get_connection",
    "get_notes",
    "get_student",
    "get_user_by_email",
    "get_user_by_id",
    "get_users",
    "get_user_progress",
    "initialize_database",
    "save_learning_progress",
    "save_local_progress",
    "save_local_submission",
    "set_note_pinned",
    "update_note",
    "update_user_profile",
    "upsert_content_item",
    "user_payload",
]
