"""Structured lesson content. One schema, blocks chosen per lesson (never all forced)."""

LOOP = ["CONCEPT", "EXPLAIN", "INTERACT", "EXPERIMENT", "PRACTICE", "REFLECT", "APPLY"]

LESSONS = {
    "friction-43": {
        "id": "friction-43", "subject_slug": "physics", "subject_name": "Physics",
        "chapter_label": "Chapter 4 · Friction & Applications",
        "title": "Lesson 4.3 · Why friction opposes motion",
        "objective": "Predict whether a box slides or grips — using μ and normal force.",
        "est": "15 min", "next_label": "Lesson 4.4 · Angle of repose",
        "blocks": [
            {"type": "text", "stage": "CONCEPT", "title": "The one idea",
             "body": "Friction opposes relative motion. Static friction adjusts itself up to a limit (μs·N); kinetic friction stays roughly constant (μk·N). If your push exceeds the limit, the box moves."},
            {"type": "visual", "stage": "EXPLAIN", "title": "See the forces", "diagram": "friction",
             "caption": "N pushes up, weight pulls down, push goes right, friction fights left."},
            {"type": "interactive", "stage": "INTERACT", "title": "Try: push the box", "widget": "slider",
             "prompt": "Drag μs and see the max grip force for a 10 kg box (N ≈ 100 N).",
             "config": {"min": 0.1, "max": 0.9, "default": 0.4, "unit": "μs"}},
            {"type": "simulation", "stage": "EXPERIMENT", "title": "Open the Friction Simulator",
             "desc": "Step 4 of 6 · set μs = 0.4, tilt to 20°, record whether it slips.", "href": "/sandbox"},
            {"type": "check", "stage": "PRACTICE", "title": "Quick check",
             "question": "A 10 kg box (N ≈ 100 N) has μs = 0.5. You push with 40 N. What happens?",
             "options": ["It slides — 40 N > 50 N limit", "It stays — 40 N < 50 N limit", "It lifts off the ground"],
             "answer": 1, "explain": "Max static grip = 0.5 × 100 = 50 N. Your 40 N push is inside the limit, so it grips."},
            {"type": "reflect", "stage": "REFLECT", "title": "Pause and connect",
             "prompt": "Where did you feel static vs kinetic friction today? (e.g. shoes, cycle brakes, duster…)"},
            {"type": "apply", "stage": "APPLY", "title": "Apply it",
             "task": "Tomorrow's lab: predict the slip angle for μs = 0.4 before touching the sim. Write your prediction in Notes."},
        ],
    },
    "quadratics-graph": {
        "id": "quadratics-graph", "subject_slug": "maths", "subject_name": "Mathematics",
        "chapter_label": "Chapter 4 · Quadratic Equations",
        "title": "Lesson 4.2 · Reading a parabola",
        "objective": "Read roots, vertex and direction straight off a quadratic graph.",
        "est": "12 min", "next_label": "Lesson 4.3 · Discriminant shortcuts",
        "blocks": [
            {"type": "text", "stage": "CONCEPT", "title": "The one idea",
             "body": "y = ax² + bx + c is a parabola. Sign of a sets direction (up/down); where it crosses the x-axis are the roots; the vertex is the turning point."},
            {"type": "visual", "stage": "EXPLAIN", "title": "Shape gallery", "diagram": "parabola",
             "caption": "a > 0 opens up (valley) · a < 0 opens down (hill). Wider = smaller |a|."},
            {"type": "interactive", "stage": "INTERACT", "title": "Try: bend the curve", "widget": "parabola",
             "prompt": "Drag a and watch the parabola flip and widen. Find an a where the curve just touches the axis.",
             "config": {"min": -3, "max": 3, "default": 1, "unit": "a"}},
            {"type": "check", "stage": "PRACTICE", "title": "Quick check",
             "question": "y = −x² + 4 crosses the x-axis at…",
             "options": ["x = −2 and x = 2", "x = 0 only", "It never crosses"],
             "answer": 0, "explain": "Set −x² + 4 = 0 → x² = 4 → x = ±2. Opens down, hilltop at (0, 4)."},
            {"type": "reflect", "stage": "REFLECT", "title": "Pause and connect",
             "prompt": "When is a parabola's vertex a maximum vs a minimum? Answer in one line."},
        ],
    },
    "loops-patterns": {
        "id": "loops-patterns", "subject_slug": "cs", "subject_name": "Computer Science",
        "chapter_label": "Chapter 4 · Loops & Patterns",
        "title": "Lesson 4.2 · for loops that build patterns",
        "objective": "Use range() and nested loops to print number patterns.",
        "est": "18 min", "next_label": "Lesson 4.3 · while loops",
        "blocks": [
            {"type": "text", "stage": "CONCEPT", "title": "The one idea",
             "body": "A for loop repeats a block. range(n) counts 0…n−1. Nest one loop inside another to build rows × columns — the outer loop picks the row, the inner builds it."},
            {"type": "code", "stage": "EXPERIMENT", "title": "Run it: staircase",
             "starter": "for i in range(1, 6):\n    print(str(i) * i)",
             "expect": "1 / 22 / 333 …", "hint": "str(i) * i repeats the digit i times."},
            {"type": "check", "stage": "PRACTICE", "title": "Quick check",
             "question": "What does range(1, 6) produce?",
             "options": ["1 2 3 4 5 6", "1 2 3 4 5", "0 1 2 3 4 5"],
             "answer": 1, "explain": "range stops BEFORE the end: 1,2,3,4,5. That's why the staircase has 5 rows."},
            {"type": "apply", "stage": "APPLY", "title": "Apply it",
             "task": "Lab task: print a 5-row reverse staircase (55555 → 1). Paste your program into the Sandbox when done."},
        ],
    },
    "acids-ph": {
        "id": "acids-ph", "subject_slug": "chemistry", "subject_name": "Chemistry",
        "chapter_label": "Chapter 4 · Acids, Bases & Salts",
        "title": "Lesson 4.2 · The pH scale in 5 minutes",
        "objective": "Classify everyday solutions as acidic, neutral or basic using pH.",
        "est": "10 min", "next_label": "Lesson 4.3 · Indicators",
        "blocks": [
            {"type": "text", "stage": "CONCEPT", "title": "The one idea",
             "body": "pH 0–14 measures H⁺ ions. Below 7 = acidic, 7 = neutral, above 7 = basic. Each step is 10× stronger."},
            {"type": "visual", "stage": "EXPLAIN", "title": "pH strip", "diagram": "ph",
             "caption": "Lemon ~2 · water 7 · soap ~10. Same strip logic as the lab kit."},
            {"type": "check", "stage": "PRACTICE", "title": "Quick check",
             "question": "Soap solution has pH 10. It is…",
             "options": ["Acidic", "Neutral", "Basic"],
             "answer": 2, "explain": "Above 7 → basic. That's why soap feels slippery."},
            {"type": "reflect", "stage": "REFLECT", "title": "Pause and connect",
             "prompt": "List 3 liquids at home and guess each pH before the titration lab."},
        ],
    },
    "coordination": {
        "id": "coordination", "subject_slug": "biology", "subject_name": "Biology",
        "chapter_label": "Chapter 4 · Control & Coordination",
        "title": "Lesson 4.1 · How a reflex wins the race",
        "objective": "Trace a reflex arc: receptor → cord → muscle, without the brain's delay.",
        "est": "12 min", "next_label": "Lesson 4.2 · Hormones vs nerves",
        "blocks": [
            {"type": "text", "stage": "CONCEPT", "title": "The one idea",
             "body": "A reflex arc skips the brain: sensory neuron → spinal cord relay → motor neuron → muscle. Shorter path = faster escape."},
            {"type": "video", "stage": "EXPLAIN", "title": "Watch: knee-jerk (offline)",
             "caption": "2-min lab recording · stored on this machine · plays without internet.", "duration": "2:04"},
            {"type": "check", "stage": "PRACTICE", "title": "Quick check",
             "question": "In a reflex arc, the signal goes…",
             "options": ["Receptor → brain → muscle", "Receptor → spinal cord → muscle", "Muscle → cord → receptor"],
             "answer": 1, "explain": "The spinal relay replies directly — the brain is informed after, not before."},
            {"type": "apply", "stage": "APPLY", "title": "Apply it",
             "task": "Pulse lab on Monday: measure your partner's reaction catch distance and note it in Practical."},
        ],
    },
}

FIRST_LESSON = {"physics": "friction-43", "maths": "quadratics-graph", "cs": "loops-patterns",
                "chemistry": "acids-ph", "biology": "coordination"}


def get_lesson(lesson_id):
    return LESSONS.get(lesson_id)
