#!/usr/bin/env python3
"""Create the complete curriculum schema module."""
from pathlib import Path

lines = []
L = lines.append

L('"""Canonical curriculum schema definitions.')
L('')
L('Pipeline stages: RAW -> EXTRACT -> VERIFY -> IMPORT -> RUNTIME')
L('"""')
L('from __future__ import annotations')
L('')
L('import json')
L('from dataclasses import dataclass, field')
L('from enum import Enum')
L('from pathlib import Path')
L('from typing import Any')
L('')
L('')
L('class Difficulty(str, Enum):')
L('    FOUNDATION = "FOUNDATION"')
L('    EASY = "EASY"')
L('    MEDIUM = "MEDIUM"')
L('    HARD = "HARD"')
L('    BOARD_LEVEL = "BOARD_LEVEL"')
L('    CHALLENGE = "CHALLENGE"')
L('')
L('')
L('class QuestionType(str, Enum):')
L('    MCQ = "MCQ"')
L('    MULTIPLE_CORRECT = "MULTIPLE_CORRECT"')
L('    TRUE_FALSE = "TRUE_FALSE"')
L('    SHORT_ANSWER = "SHORT_ANSWER"')
L('    LONG_ANSWER = "LONG_ANSWER"')
L('    APPLICATION = "APPLICATION"')
L('    SCENARIO_BASED = "SCENARIO_BASED"')
L('    COMPETENCY_BASED = "COMPETENCY_BASED"')
L('    ASSERTION_REASON = "ASSERTION_REASON"')
L('    FILL_BLANK = "FILL_BLANK"')
L('    NUMERICAL = "NUMERICAL"')
L('    CASE_BASED = "CASE_BASED"')
L('    DIAGRAM_BASED = "DIAGRAM_BASED"')
L('')
L('')
L('class VerificationStatus(str, Enum):')
L('    PENDING = "PENDING"')
L('    AI_GENERATED = "AI_GENERATED"')
L('    VERIFIED = "VERIFIED"')
L('    REJECTED = "REJECTED"')
L('')
L('')
L('class CompetencyCategory(str, Enum):')
L('    REMEMBER = "Remember"')
L('    UNDERSTAND = "Understand"')
L('    APPLY = "Apply"')
L('    ANALYZE = "Analyze"')
L('    EVALUATE = "Evaluate"')
L('    CREATE = "Create"')
L('')
L('')
L('class Board(str, Enum):')
L('    CBSE = "CBSE"')
L('    NCERT = "NCERT"')
L('')
L('')
L('CANONICAL_SCHEMA_VERSION = "2026.09.1"')
L('SCHEMA_DOC = Path(__file__).resolve().parent / "schema_doc.json"')
L('')
L('')

Path('app/schemas/curriculum.py').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print(f"Base written: {len(lines)} lines")
