"""Generate curriculum schema module."""
from pathlib import Path

lines = []
lines.append('"""Canonical curriculum schema definitions.')
lines.append('')
lines.append('Pipeline stages: RAW -> EXTRACT -> VERIFY -> IMPORT -> RUNTIME')
lines.append('"""')
lines.append('from __future__ import annotations')
lines.append('')
lines.append('import json')
lines.append('from dataclasses import dataclass, field')
lines.append('from enum import Enum')
lines.append('from pathlib import Path')
lines.append('from typing import Any')
lines.append('')
lines.append('class Difficulty(str, Enum):')
lines.append('    FOUNDATION = "FOUNDATION"')
lines.append('    EASY = "EASY"')
lines.append('    MEDIUM = "MEDIUM"')
lines.append('    HARD = "HARD"')
lines.append('    BOARD_LEVEL = "BOARD_LEVEL"')
lines.append('    CHALLENGE = "CHALLENGE"')
lines.append('')
lines.append('class QuestionType(str, Enum):')
lines.append('    MCQ = "MCQ"')
lines.append('    MULTIPLE_CORRECT = "MULTIPLE_CORRECT"')
lines.append('    TRUE_FALSE = "TRUE_FALSE"')
lines.append('    SHORT_ANSWER = "SHORT_ANSWER"')
lines.append('    LONG_ANSWER = "LONG_ANSWER"')
lines.append('    APPLICATION = "APPLICATION"')
lines.append('    SCENARIO_BASED = "SCENARIO_BASED"')
lines.append('    COMPETENCY_BASED = "COMPETENCY_BASED"')
lines.append('    ASSERTION_REASON = "ASSERTION_REASON"')
lines.append('    FILL_BLANK = "FILL_BLANK"')
lines.append('    NUMERICAL = "NUMERICAL"')
lines.append('    CASE_BASED = "CASE_BASED"')
lines.append('    DIAGRAM_BASED = "DIAGRAM_BASED"')
lines.append('')
lines.append('class CompetencyCategory(str, Enum):')
lines.append('    REMEMBER = "Remember"')
lines.append('    UNDERSTAND = "Understand"')
lines.append('    APPLY = "Apply"')
lines.append('    ANALYZE = "Analyze"')
lines.append('    EVALUATE = "Evaluate"')
lines.append('    CREATE = "Create"')
lines.append('')
lines.append('class Board(str, Enum):')
lines.append('    CBSE = "CBSE"')
lines.append('    NCERT = "NCERT"')
lines.append('')
lines.append('CANONICAL_SCHEMA_VERSION = "2026.09.1"')
lines.append('SCHEMA_DOC = Path(__file__).resolve().parent / "schema_doc.json"')

Path('app/schemas/curriculum.py').write_text('\n'.join(lines), encoding='utf-8')
print("Part 1 written")
