"""Generate curriculum schema module - SourceMetadata, Concept, SubConcept."""
from pathlib import Path

lines = []
lines.append('@dataclass')
lines.append('class SourceMetadata:')
lines.append('    source_id: str')
lines.append('    source_type: str')
lines.append('    title: str')
lines.append('    publisher: str | None = None')
lines.append('    url: str | None = None')
lines.append('    version: str | None = None')
lines.append('    academic_year: str | None = None')
lines.append('    accessed_at: str | None = None')
lines.append('    checksum_sha256: str | None = None')
lines.append('    notes: str | None = None')
lines.append('')
lines.append('    def to_dict(self) -> dict:')
lines.append('        d = {"source_id": self.source_id, "source_type": self.source_type, "title": self.title}')
lines.append('        for k in ("publisher", "url", "version", "academic_year", "accessed_at", "checksum_sha256", "notes"):')
lines.append('            v = getattr(self, k, None)')
lines.append('            if v is not None: d[k] = v')
lines.append('        return d')
lines.append('')
lines.append('    @classmethod')
lines.append('    def from_dict(cls, data: dict) -> SourceMetadata:')
lines.append('        return cls(**{k: v for k, v in data.items() if v is not None})')
lines.append('')
lines.append('')
lines.append('@dataclass')
lines.append('class Concept:')
lines.append('    concept_id: str')
lines.append('    title: str')
lines.append('    description: str | None = None')
lines.append('    explanation: str | None = None')
lines.append('    difficulty: Difficulty = Difficulty.EASY')
lines.append('    learning_objectives: list[str] = field(default_factory=list)')
lines.append('    prerequisites: list[str] = field(default_factory=list)')
lines.append('    next_concepts: list[str] = field(default_factory=list)')
lines.append('    competencies: list[CompetencyCategory] = field(default_factory=list)')
lines.append('    activities: list[str] = field(default_factory=list)')
lines.append('    simulation_ids: list[str] = field(default_factory=list)')
lines.append('    source: SourceMetadata | None = None')
lines.append('    verified: bool = False')
lines.append('    verified_at: str | None = None')
lines.append('    ai_generation_notes: str | None = None')
lines.append('')
lines.append('    def to_dict(self) -> dict:')
lines.append('        d = {"concept_id": self.concept_id, "title": self.title, "verified": self.verified}')
lines.append('        if self.description: d["description"] = self.description')
lines.append('        if self.explanation: d["explanation"] = self.explanation')
lines.append('        d["difficulty"] = self.difficulty.value')
lines.append('        if self.learning_objectives: d["learning_objectives"] = self.learning_objectives')
lines.append('        if self.prerequisites: d["prerequisites"] = self.prerequisites')
lines.append('        if self.next_concepts: d["next_concepts"] = self.next_concepts')
lines.append('        if self.competencies: d["competencies"] = [c.value for c in self.competencies]')
lines.append('        if self.activities: d["activities"] = self.activities')
lines.append('        if self.simulation_ids: d["simulation_ids"] = self.simulation_ids')
lines.append('        if self.source: d["source"] = self.source.to_dict()')
lines.append('        if self.verified_at: d["verified_at"] = self.verified_at')
lines.append('        if self.ai_generation_notes: d["ai_generation_notes"] = self.ai_generation_notes')
lines.append('        return d')
lines.append('')
lines.append('    @classmethod')
lines.append('    def from_dict(cls, data: dict) -> Concept:')
lines.append('        comps = [CompetencyCategory(v) for v in data.get("competencies", [])]')
lines.append('        return cls(')
lines.append('            concept_id=data["concept_id"], title=data["title"],')
lines.append('            description=data.get("description"), explanation=data.get("explanation"),')
lines.append('            difficulty=Difficulty(data.get("difficulty", "EASY")),')
lines.append('            learning_objectives=data.get("learning_objectives", []),')
lines.append('            prerequisites=data.get("prerequisites", []),')
lines.append('            next_concepts=data.get("next_concepts", []),')
lines.append('            competencies=comps, activities=data.get("activities", []),')
lines.append('            simulation_ids=data.get("simulation_ids", []),')
lines.append('            source=SourceMetadata.from_dict(data["source"]) if data.get("source") else None,')
lines.append('            verified=data.get("verified", False), verified_at=data.get("verified_at"),')
lines.append('            ai_generation_notes=data.get("ai_generation_notes"),')
lines.append('        )')
lines.append('')
lines.append('')
lines.append('@dataclass')
lines.append('class SubConcept:')
lines.append('    sub_concept_id: str')
lines.append('    concept_id: str')
lines.append('    title: str')
lines.append('    description: str | None = None')
lines.append('    verified: bool = False')
lines.append('')
lines.append('    def to_dict(self) -> dict:')
lines.append('        d = {"sub_concept_id": self.sub_concept_id, "concept_id": self.concept_id,')
lines.append('             "title": self.title, "verified": self.verified}')
lines.append('        if self.description: d["description"] = self.description')
lines.append('        return d')
lines.append('')
lines.append('    @classmethod')
lines.append('    def from_dict(cls, data: dict) -> SubConcept:')
lines.append('        return cls(sub_concept_id=data["sub_concept_id"], concept_id=data["concept_id"],')
lines.append('                   title=data["title"], description=data.get("description"),')
lines.append('                   verified=data.get("verified", False))')

Path('app/schemas/curriculum.py').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print("Part 2 written")
