#!/usr/bin/env python3
"""Generate curriculum schema part 1 - Enums and SourceMetadata."""
from pathlib import Path

c = []
w = c.append
w('"""Canonical curriculum schema."""')
w('from __future__ import annotations')
w('import json')
w('from dataclasses import dataclass, field')
w('from enum import Enum')
w('from pathlib import Path')
w('from typing import Any')
w('')
w('class Difficulty(str, Enum):')
w('    FOUNDATION="FOUNDATION";EASY="EASY";MEDIUM="MEDIUM";HARD="HARD";BOARD_LEVEL="BOARD_LEVEL";CHALLENGE="CHALLENGE"')
w('')
w('class QuestionType(str, Enum):')
w('    MCQ="MCQ";MULTIPLE_CORRECT="MULTIPLE_CORRECT";TRUE_FALSE="TRUE_FALSE";SHORT_ANSWER="SHORT_ANSWER";LONG_ANSWER="LONG_ANSWER";APPLICATION="APPLICATION";SCENARIO_BASED="SCENARIO_BASED";COMPETENCY_BASED="COMPETENCY_BASED";ASSERTION_REASON="ASSERTION_REASON";FILL_BLANK="FILL_BLANK";NUMERICAL="NUMERICAL";CASE_BASED="CASE_BASED";DIAGRAM_BASED="DIAGRAM_BASED"')
w('')
w('class CompetencyCategory(str, Enum):')
w('    REMEMBER="Remember";UNDERSTAND="Understand";APPLY="Apply";ANALYZE="Analyze";EVALUATE="Evaluate";CREATE="Create"')
w('')
w('class Board(str, Enum):')
w('    CBSE="CBSE";NCERT="NCERT"')
w('')
w('CANONICAL_SCHEMA_VERSION="2026.09.1"')
w('SCHEMA_DOC=Path(__file__).resolve().parent/"schema_doc.json"')
w('')
w('')
w('@dataclass')
w('class SourceMetadata:')
w('    source_id:str;source_type:str;title:str')
w('    publisher:str|None=None;url:str|None=None;version:str|None=None')
w('    academic_year:str|None=None;accessed_at:str|None=None')
w('    checksum_sha256:str|None=None;notes:str|None=None')
w('    def to_dict(self)->dict:')
w('        d={"source_id":self.source_id,"source_type":self.source_type,"title":self.title}')
w('        for k in("publisher","url","version","academic_year","accessed_at","checksum_sha256","notes"):')
w('            v=getattr(self,k,None)')
w('            if v is not None:d[k]=v')
w('        return d')
w('    @classmethod')
w('    def from_dict(cls,data:dict)->SourceMetadata:')
w('        return cls(**{k:v for k,v in data.items() if v is not None})')
w('')
Path('app/schemas/curriculum.py').write_text('\n'.join(c),encoding='utf-8')
print(f"Part 1: {len(c)} lines")
