#!/usr/bin/env python3
"""Generate curriculum schema part 2 - Concept, SubConcept."""
from pathlib import Path

c = []
w = c.append
w('')
w('@dataclass')
w('class Concept:')
w('    """A curriculum concept with prerequisites and competencies."""')
w('    concept_id:str')
w('    title:str')
w('    description:str|None=None')
w('    explanation:str|None=None')
w('    difficulty:Degree=Easy.EASY')
w('    learning_objectives:list[str]=field(default_factory=list)')
w('    prerequisites:list[str]=field(default_factory=list)')
w('    next_concepts:list[str]=field(default_factory=list)')
w('    competencies:list[CompetencyCategory]=field(default_factory=list)')
w('    activities:list[str]=field(default_factory=list)')
w('    simulation_ids:list[str]=field(default_factory=list)')
w('    source:SourceMetadata|None=None')
w('    verified:bool=False')
w('    verified_at:str|None=None')
w('    ai_generation_notes:str|None=None')
w('')
w('    def to_dict(self)->dict:')
w('        d={"concept_id":self.concept_id,"title":self.title,"verified":self.verified}')
w('        for k in("description","explanation"):')
w('            v=getattr(self,k,None)')
w('            if v:d[k]=v')
w('        d["difficulty"]=self.difficulty.value')
w('        for k in("learning_objectives","prerequisites","next_concepts","competencies","activities","simulation_ids"):')
w('            v=getattr(self,k,None)')
w('            if v:d[k]=v if k!="competencies" else [c.value for c in v]')
w('        if self.source:d["source"]=self.source.to_dict()')
w('        for k in("verified_at","ai_generation_notes"):')
w('            v=getattr(self,k,None)')
w('            if v:d[k]=v')
w('        return d')
w('')
w('    @classmethod')
w('    def from_dict(cls,data:dict)->"Concept":')
w('        comps=[CompetencyCategory(v) for v in data.get("competencies",[])]')
w('        return cls(')
w('            concept_id=data["concept_id"],title=data["title"],')
w('            description=data.get("description"),explanation=data.get("explanation"),')
w('            difficulty=Difficulty(data.get("difficulty","EASY")),')
w('            learning_objectives=data.get("learning_objectives",[]),')
w('            prerequisites=data.get("prerequisites",[]),')
w('            next_concepts=data.get("next_concepts",[]),')
w('            competencies=comps,activities=data.get("activities",[]),')
w('            simulation_ids=data.get("simulation_ids",[]),')
w('            source=SourceMetadata.from_dict(data["source"]) if data.get("source") else None,')
w('            verified=data.get("verified",False),verified_at=data.get("verified_at"),')
w('            ai_generation_notes=data.get("ai_generation_notes"),')
w('        )')
w('')
w('')
w('@dataclass')
w('class SubConcept:')
w('    sub_concept_id:str')
w('    concept_id:str')
w('    title:str')
w('    description:str|None=None')
w('    verified:bool=False')
w('    def to_dict(self)->dict:')
w('        d={"sub_concept_id":self.sub_concept_id,"concept_id":self.concept_id,"title":self.title,"verified":self.verified}')
w('        if self.description:d["description"]=self.description')
w('        return d')
w('    @classmethod')
w('    def from_dict(cls,data:dict)->"SubConcept":')
w('        return cls(sub_concept_id=data["sub_concept_id"],concept_id=data["concept_id"],')
w('                   title=data["title"],description=data.get("description"),')
w('                   verified=data.get("verified",False))')
w('')

Path('app/schemas/curriculum.py').write_text(
    Path('app/schemas/curriculum.py').read_text(encoding='utf-8') + '\n'.join(c),
    encoding='utf-8'
)
print(f"Part 2 appended: {len(c)} lines")
