#!/usr/bin/env python3
"""Generate the complete curriculum schema module."""
from pathlib import Path

OUT = Path('app/schemas/curriculum.py')

lines = []
a = lines.append

a('"""Canonical curriculum schema definitions.')
a('')
a('Pipeline stages: RAW -> EXTRACT -> VERIFY -> IMPORT -> RUNTIME')
a('"""')
a('from __future__ import annotations')
a('')
a('import json')
a('from dataclasses import dataclass, field')
a('from enum import Enum')
a('from pathlib import Path')
a('from typing import Any')
a('')
a('')
a('class Difficulty(str, Enum):')
a('    FOUNDATION = "FOUNDATION"')
a('    EASY = "EASY"')
a('    MEDIUM = "MEDIUM"')
a('    HARD = "HARD"')
a('    BOARD_LEVEL = "BOARD_LEVEL"')
a('    CHALLENGE = "CHALLENGE"')
a('')
a('')
a('class QuestionType(str, Enum):')
a('    MCQ = "MCQ"')
a('    MULTIPLE_CORRECT = "MULTIPLE_CORRECT"')
a('    TRUE_FALSE = "TRUE_FALSE"')
a('    SHORT_ANSWER = "SHORT_ANSWER"')
a('    LONG_ANSWER = "LONG_ANSWER"')
a('    APPLICATION = "APPLICATION"')
a('    SCENARIO_BASED = "SCENARIO_BASED"')
a('    COMPETENCY_BASED = "COMPETENCY_BASED"')
a('    ASSERTION_REASON = "ASSERTION_REASON"')
a('    FILL_BLANK = "FILL_BLANK"')
a('    NUMERICAL = "NUMERICAL"')
a('    CASE_BASED = "CASE_BASED"')
a('    DIAGRAM_BASED = "DIAGRAM_BASED"')
a('')
a('')
a('class VerificationStatus(str, Enum):')
a('    PENDING = "PENDING"')
a('    AI_GENERATED = "AI_GENERATED"')
a('    VERIFIED = "VERIFIED"')
a('    REJECTED = "REJECTED"')
a('')
a('')
a('class CompetencyCategory(str, Enum):')
a('    REMEMBER = "Remember"')
a('    UNDERSTAND = "Understand"')
a('    APPLY = "Apply"')
a('    ANALYZE = "Analyze"')
a('    EVALUATE = "Evaluate"')
a('    CREATE = "Create"')
a('')
a('')
a('class Board(str, Enum):')
a('    CBSE = "CBSE"')
a('    NCERT = "NCERT"')
a('')
a('')
a('CANONICAL_SCHEMA_VERSION = "2026.09.1"')
a('SCHEMA_DOC = Path(__file__).resolve().parent / "schema_doc.json"')
a('')
a('')

OUT.write_text('\n'.join(lines), encoding='utf-8')
print(f"Base written: {len(lines)} lines")
